export default {
    GET_NEWS_FEED:"GET_NEWS_FEED",
    SELECT_NEWS:"SELECT_NEWS",
    OPEN_EDIT_ARTICLE:"OPEN_EDIT_ARTICLE",
    SAVE_EDIT_ARTICLE:"SAVE_EDIT_ARTICLE",
    SAVE_ARTICLE:"SAVE_ARTICLE",
    SHOW_FORM:"SHOW_FORM",
    GET_ARTICLE_INPUT:"GET_ARTICLE_INPUT",
    TOGGLE_APROVE:"TOGGLE_APROVE"
  };