export default {
  GET_REGISTER_INPUT:"GET_REGISTER_INPUT",
  REGISTER_USER:"REGISTER_USER",
  SAVE_TOKEN:"SAVE_TOKEN",
  GET_CURRENT_USER:"GET_CURRENT_USER",
  ESTABLISH_CURRENT_USER:"ESTABLISH_CURRENT_USER",
  LOGOUT_USER:"LOGOUT_USER"
};