export default {
  GET_LOGIN_INPUT:"GET_LOGIN_INPUT",
  LOGIN_USER:"LOGIN_USER",
  SAVE_TOKEN:"SAVE_TOKEN",
  GET_CURRENT_USER:"GET_CURRENT_USER",
  ESTABLISH_CURRENT_USER:"ESTABLISH_CURRENT_USER",
  LOGOUT_USER:"LOGOUT_USER"
};